-- Removes only local browser-test cards and records owned by them.
-- The name prefix is generated by tests/e2e/manual-workflow.spec.ts.

PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

-- Browser audits may create sources while exercising a pre-existing card.
-- Remove only records carrying the test-only title prefix.
DELETE FROM audit_events
WHERE entity_id IN (
  SELECT id FROM sources WHERE title LIKE 'E2E Functional Source%'
);

DELETE FROM sources
WHERE title LIKE 'E2E Functional Source%';

DELETE FROM audit_events
WHERE entity_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
   OR entity_id IN (
     SELECT id FROM fights
     WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
   )
   OR entity_id IN (
     SELECT id FROM sources
     WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
   )
   OR entity_id IN (
     SELECT id FROM extraction_runs
     WHERE source_id IN (
       SELECT id FROM sources
       WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
     )
   )
   OR entity_id IN (
     SELECT id FROM synthesis_runs
     WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
   )
   OR entity_id IN (
     SELECT id FROM bets
     WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
   );

DELETE FROM bet_support
WHERE bet_id IN (
  SELECT id FROM bets
  WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
);

DELETE FROM bet_legs
WHERE bet_id IN (
  SELECT id FROM bets
  WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
);

DELETE FROM bets
WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %');

DELETE FROM fight_summaries
WHERE synthesis_run_id IN (
  SELECT id FROM synthesis_runs
  WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
);

DELETE FROM market_prices
WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %');

DELETE FROM fight_stats
WHERE source_id IN (
  SELECT id FROM sources
  WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
);

DELETE FROM capper_tips
WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %');

DELETE FROM fight_opinions
WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %');

DELETE FROM extraction_review_items
WHERE extraction_run_id IN (
  SELECT id FROM extraction_runs
  WHERE source_id IN (
    SELECT id FROM sources
    WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
  )
);

UPDATE sources
SET active_extraction_run_id = NULL
WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %');

DELETE FROM extraction_runs
WHERE source_id IN (
  SELECT id FROM sources
  WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
);

DELETE FROM sources
WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %');

DELETE FROM fight_outcomes
WHERE fight_id IN (
  SELECT id FROM fights
  WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
);

DELETE FROM fight_participants
WHERE fight_id IN (
  SELECT id FROM fights
  WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %')
);

DELETE FROM synthesis_runs
WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %');

DELETE FROM fights
WHERE card_id IN (SELECT id FROM cards WHERE name LIKE 'E2E UFC Card %');

DELETE FROM cards
WHERE name LIKE 'E2E UFC Card %';

DELETE FROM fighter_aliases
WHERE fighter_id IN (
  SELECT id FROM fighters WHERE canonical_name LIKE 'E2E Fighter %'
);

DELETE FROM fighters
WHERE canonical_name LIKE 'E2E Fighter %'
  AND NOT EXISTS (
    SELECT 1 FROM fight_participants WHERE fighter_id = fighters.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM market_prices WHERE selection_fighter_id = fighters.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM fight_opinions WHERE picked_fighter_id = fighters.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM capper_tips WHERE selection_fighter_id = fighters.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM fight_outcomes WHERE winner_fighter_id = fighters.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM fight_summaries WHERE consensus_fighter_id = fighters.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM bet_legs WHERE selection_fighter_id = fighters.id
  );

DELETE FROM capper_aliases
WHERE capper_id IN (
  SELECT id FROM cappers WHERE name LIKE 'E2E Capper %'
);

DELETE FROM cappers
WHERE name LIKE 'E2E Capper %'
  AND NOT EXISTS (
    SELECT 1 FROM sources WHERE primary_capper_id = cappers.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM fight_opinions WHERE capper_id = cappers.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM capper_tips WHERE capper_id = cappers.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM bet_support WHERE capper_id = cappers.id
  );

COMMIT;
